export const ADD_VIDEO_TO_LIST = 'ADD_VIDEO_TO_LIST';
export const REMOVE_VIDEO_FROM_LIST = 'REMOVE_VIDEO_FROM_LIST';
export const USER_LOGIN_SET_INFO = 'USER_LOGIN_SET_INFO';
export const USER_LOGIN_REMOVE_INFO = 'USER_LOGIN_REMOVE_INFO';
